<a href="https://colab.research.google.com/github/alexandramontejo/Linear-Algebra_ChE_2nd-Sem-2021-2022/blob/main/Activity_2_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Linear ALgebra for ChE
## Assigment : Matrices
Now that you have a fundamental knowledge about Python, we'll try to look into greater dimensions.

### Objectives
At the end of this activity you will be able to:
1. Be familiar with matrices and their relation to linear equations.
2. Perform basic matrix operations.
3. Program and translate matrix equations and operations using Python.


#Discussion

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline


###Matrices
The notation and use of matrices is probably one of the fundamentals of modern computing. Matrices are also handy representations of complex equations or multiple inter-related equations from 2-dimensional equations to even hundreds and thousands of them.

Let's say for example you have A and B as system of equation.

$$
A = \left\{
    \begin{array}\
        x + y \\ 
        4x - 10y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        x+y+z \\ 
        3x -2y -z \\
        -x + 4y +2z
    \end{array}
\right. \\
C = \left\{
    \begin{array}\
      w-2x+3y-4z \\
      3w-x-2y+z \\
      2w -x+3y-2z
    \end{array}
\right.
$$

We could see that A is a system of 2 equations with 2 parameters. While B isa a system of 3 equations with 3 parameters. We can represent them as matrices as:

$$
A=\begin{bmatrix} 1 & 1 \\ 4 & {-10}\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end{bmatrix}\\
C = \begin{bmatrix} 1& -2 & 3 & -4 \\ 3 & -1 & -2 & 1 \\ 2 & -1 & 3 & -2\end{bmatrix}
$$


Just like our previous laboratory activity, we'll represent system of lienar equations as a matrix. The entities or numbers in matrices are called the elements of a matrix. These elements are arranged and ordered in rows and columns which form the list/array-like structures of matrices. And just like arrays, these elements are indezed according their position with respect to their rows and columns. This can be represented just like the equation below. Whereas A is a matrix consisting of elements denoted by aij. Denoted by i is the number of rows in the matrix while j stands for the numner of columns. Do note that the size of a matrix is i x j.

#Declaring Matrices
We already gone over some of the types of matrices as vectors byt we'll further discuss them in this laboratory activity.

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$


In [2]:
## Since we'll keep on describing matrices; let's make a function.
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')


In [3]:
## Declaring a 2x2 matrix
A = np.array([
    [1, 2],
    [3, 1]
])
describe_mat(A)

Matrix:
[[1 2]
 [3 1]]

Shape:	(2, 2)
Rank:	2



In [4]:
G = np.array([
    [1,1,3],
    [2,2,4]
])
describe_mat(G)


Matrix:
[[1 1 3]
 [2 2 4]]

Shape:	(2, 3)
Rank:	2



In [5]:
## Declaring 3x2 matrix
B = np.array([
    [8, 2],
    [5, 4],
    [1, 1]
])
describe_mat(B)


Matrix:
[[8 2]
 [5 4]
 [1 1]]

Shape:	(3, 2)
Rank:	2



In [6]:
H = np.array([1,2,3,4])
describe_mat(H)


Matrix:
[1 2 3 4]

Shape:	(4,)
Rank:	1



#Categorizing Matrices
There are several ways of classifying matrices...

###According to shape

###Row and Column Matrices

In [7]:
## Declaring a Row Matrix
rowmatrix1D = np.array([
    1, 3, 2, -4
]) ## this is a 1-D Matrix with a shape of (3,), it's not really considered as a row matrix.
row_mat_2D = np.array([
    [1,2,3, -4]
]) ## this is a 2-D Matrix with a shape of (1,3)
describe_mat(rowmatrix1D)
describe_mat(row_mat_2D)


Matrix:
[ 1  3  2 -4]

Shape:	(4,)
Rank:	1

Matrix:
[[ 1  2  3 -4]]

Shape:	(1, 4)
Rank:	2



In [8]:
## Declaring a column matrix
col_mat = np.array([
    [15],
    [7],
    [30]
]) ## this is a 2-D Matrix with a shape of (3,1)
describe_mat(col_mat)


Matrix:
[[15]
 [ 7]
 [30]]

Shape:	(3, 1)
Rank:	2



###Square Matrix
Matrices that have the same row and column sizes. We could say a matrix is square if i = j. We can tweak our matrix descriptor function to determine square matrices.

In [9]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False 
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')


In [10]:
square_mat = np.array([
    [15,7,11],
    [13,63,98],
    [56,17,21]
])

non_square_mat = np.array([
    [16,72,50],
    [13,39,84]
])
describe_mat(square_mat)
describe_mat(non_square_mat)


Matrix:
[[15  7 11]
 [13 63 98]
 [56 17 21]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[16 72 50]
 [13 39 84]]

Shape:	(2, 3)
Rank:	2
Is Square: False



##According to element values

###Null Matrix
A Null Matrix is a matrix that has no elements. Its always a subspace of any vector or matrix

lorem ipsum

In [11]:
def describe_mat(matrix):
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False 
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
        print('Matrix is Null')


In [12]:
## null[]
null_mat = np.array([[0]])
describe_mat(null_mat)


Matrix:
[[0]]

Shape:	(1, 1)
Rank:	2
Is Square: True



###Zero Matrix
A zero matrix can be any rectangular matrix but with all elements having a value of 0.

In [13]:
zero_mat_row = np.zeros((1,2))
zero_mat_sqr = np.zeros((2,2))
zero_mat_rct = np.zeros((3,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')


Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0.]
 [0. 0.]]
Zero Rectangular Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


##Ones Matrix
Just like the zero matrix, ones matrix can be any rectangular matrix but all of its elements are 1s instead of 0s.

lorem ipsum

In [14]:
ones_mat_row = np.ones((1,2))
ones_mat_sqr = np.ones((2,2))
ones_mat_rct = np.ones((3,2))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')


Ones Row Matrix: 
[[1. 1.]]
Ones Square Matrix: 
[[1. 1.]
 [1. 1.]]
Ones Rectangular Matrix: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


###Diagonal Matrix
A diagonal matrix is a square matrix that has values only at the diagonal of the matrix.

In [15]:
np.array([
    [2,0,0],
    [0,3,0],
    [0,0,5]
])


array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

In [16]:
d = np.diag([12,53,15,27])
#d.shape[0] == d.shape[1]
d

array([[12,  0,  0,  0],
       [ 0, 53,  0,  0],
       [ 0,  0, 15,  0],
       [ 0,  0,  0, 27]])

###Identity Matrix
An identity matrix is a special diagonal matrix in which the values at the diagonal are ones.

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

##Upper Triangular Matrix
An upper triangular matrix is a matrix that has no values below the diagonal.

In [19]:
np.array([
   [1,2,3,4],
   [0,3,1,-1],
   [0.0,5,2],
   [0,0,0,2]
])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  """


array([list([1, 2, 3, 4]), list([0, 3, 1, -1]), list([0.0, 5, 2]),
       list([0, 0, 0, 2])], dtype=object)

In [20]:
F = np.array([
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
])
np.triu(F)


array([[ 2, -3,  4, -5,  6],
       [ 0, -3,  4, -5,  6],
       [ 0,  0,  4, -5,  6],
       [ 0,  0,  0, -5,  6],
       [ 0,  0,  0,  0,  6]])

##Lower Triangular Matrix

In [21]:
np.tril(F)

array([[ 2,  0,  0,  0,  0],
       [ 2, -3,  0,  0,  0],
       [ 2, -3,  4,  0,  0],
       [ 2, -3,  4, -5,  0],
       [ 2, -3,  4, -5,  6]])

In [22]:
np.array([
    [17,0,0],
    [85,23,0],
    [9,18,55]
])

array([[17,  0,  0],
       [85, 23,  0],
       [ 9, 18, 55]])

#Practice

1. Given the linear combination below, try to create a corresponding matrix representing it.


:$$\theta = 5x + 3y - z$$


In [ ]:
num_1 = np.array([
    [5,3,-1],
])
print (num_1)

[[ 5  3 -1]]


2. Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.


$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$


In [ ]:
num_2 = np.array([
    [1,2,1],
    [0,4,-1],
    [0,0,0]
])
describe_mat(num_2)

Matrix:
[[ 1  2  1]
 [ 0  4 -1]
 [ 0  0  0]]

Shape:	(3, 3)
Rank:	2
Is Square: True



3. Given the matrix below, express it as a linear combination in a markdown and a LaTeX markdown


In [ ]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])


Answer

Linear combination
$$
G = \left\{
    \begin{array}\
      x_1+7x_2+8x_3 \\
      2x_1+2x_2-2y_3 \\
      4x_1 + 6x_2 +7x_3
    \end{array}
\right.
$$

LaTex
$$
G=\begin{bmatrix} 1 & 7 & 8 \\ 2 & 2 & 2 \\ 4 & 6 & 7\end{bmatrix}\\
$$

4. Given the matrix below, display the output as a LaTeX markdown also express it as a system of linear combinations.


In [ ]:
H = np.tril(G)
H


array([[1, 0, 0],
       [2, 2, 0]])

Answer

Linear combination
$$
H = \left\{
    \begin{array}\
      x_1\\
      2x_1+2x_2\\
      4x_1 + 6x_2 +7x_3
    \end{array}
\right.
$$

LaTex
$$
G=\begin{bmatrix} 1 & 0 & 0 \\ 2 & 2 & 0 \\ 4 & 6 & 7\end{bmatrix}\\
$$

###ADDITION


In [23]:
A = np.array([
    [4,6],
    [9,7],
    [6,3]
])
B = np.array([
    [7,8],
    [1,1],
    [6,4]
])
A+B


array([[11, 14],
       [10,  8],
       [12,  7]])

In [24]:
2+A ##Broadcasting
# 2*np.ones(A.shape)+A

array([[ 6,  8],
       [11,  9],
       [ 8,  5]])

###SUBTRACTION


In [25]:
A-B

array([[-3, -2],
       [ 8,  6],
       [ 0, -1]])

In [ ]:
3-B == 3*np.ones(B.shape)-B

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

###ELEMENT-WISE MULTIPLICATION

In [26]:
A*B
np.multiply(A,B)

array([[28, 48],
       [ 9,  7],
       [36, 12]])

In [27]:
2*A

array([[ 8, 12],
       [18, 14],
       [12,  6]])

In [ ]:
A@B

ValueError: ignored

In [28]:
alpha=10**-10
A/(alpha+B)

array([[0.57142857, 0.75      ],
       [9.        , 7.        ],
       [1.        , 0.75      ]])

In [29]:
np.add(A,B)

array([[11, 14],
       [10,  8],
       [12,  7]])

#Activity

##Task 1
Create a function named mat_desc() that througouhly describes a matrix, it should:

  1. Displays the shape, size, and rank of the matrix.
  2. Displays whether the matrix is square or non-square.
  3. Displays whether the matrix is an empty matrix.
  4. Displays if the matrix is an identity, ones, or zeros matrix

Use 5 sample matrices in which their shapes are not lower than (3,3) . In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [30]:
# mat_desc function

def mat_desc(mat):
  sq = False
  mat = np.array(mat)
  print(mat)
  print('Shape', mat.shape)
  print('Size', mat.size)
  print('Rank', np.linalg.matrix_rank(mat))
  if(mat.shape[0] == mat.shape[1]):
    sq = True
    print('Square Matrix')
  else: 
    print('Non-Square Matrix')
  if(mat.shape[0] == 0 and mat.shape[1] == 0):
    print('Empty Matrix')
  else:
    print('Matrix in not empty')
  iden = np.identity(mat.shape[0])
  if(sq and (iden == mat).all()):
    print('Identity Matrix')
  else:
    print('Not identity matrix')
  one = np.ones((mat.shape[0], mat.shape[1]))
  if(one == mat).all ():
    print('Ones matrix')
  else:
    print('Not a Ones Matrix')
  zero = np.zeros((mat.shape[0], mat.shape[1]))
  if((zero == mat).all()):
    print('Zero Matrix')
  else:
    print('Non-Zero Matrix')

In [31]:
print('Matrix A:')
mat_desc([
    [5,7,8],
    [1,3,7],
    [7,8,30],
    [6,7,17]
])
print('Matrix B:')
mat_desc([
    [0,0,0],
    [0,0,0],
    [0,0,0],
    [0,0,0]
])
print('Matrix C:')
mat_desc([
    [45,17,58,90],
    [40, 86, 87, 76],
    [95, 100, 91, 98],
    [45, 87, 92, 41],
    [76, 98, 70, 45]
])
print('Matrix D:')
mat_desc([
    [1,1,1,1,1],
    [1,1,1,1,1],
    [1,1,1,1,1],
    [1,1,1,1,1],
    [1,1,1,1,1],
    [1,1,1,1,1]
])
print('Matrix E:')
mat_desc([
    [0,1,1,1,1],
    [1,1,0,1,1],
    [1,1,1,0,1],
    [1,1,1,1,0],
    [1,1,1,0,1],
    [1,1,1,1,1]
])



Matrix A:
[[ 5  7  8]
 [ 1  3  7]
 [ 7  8 30]
 [ 6  7 17]]
Shape (4, 3)
Size 12
Rank 3
Non-Square Matrix
Matrix in not empty
Not identity matrix
Not a Ones Matrix
Non-Zero Matrix
Matrix B:
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
Shape (4, 3)
Size 12
Rank 0
Non-Square Matrix
Matrix in not empty
Not identity matrix
Not a Ones Matrix
Zero Matrix
Matrix C:
[[ 45  17  58  90]
 [ 40  86  87  76]
 [ 95 100  91  98]
 [ 45  87  92  41]
 [ 76  98  70  45]]
Shape (5, 4)
Size 20
Rank 4
Non-Square Matrix
Matrix in not empty
Not identity matrix
Not a Ones Matrix
Non-Zero Matrix
Matrix D:
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
Shape (6, 5)
Size 30
Rank 1
Non-Square Matrix
Matrix in not empty
Not identity matrix
Ones matrix
Non-Zero Matrix
Matrix E:
[[0 1 1 1 1]
 [1 1 0 1 1]
 [1 1 1 0 1]
 [1 1 1 1 0]
 [1 1 1 0 1]
 [1 1 1 1 1]]
Shape (6, 5)
Size 30
Rank 5
Non-Square Matrix
Matrix in not empty
Not identity matrix
Not a Ones Matrix
Non-Zero Matrix


Create a function named `mat_operations()` that takes in two matrices a input parameters it should:<br>
 1. Determines if the matrices are viable for operation and returns your own error message if they are not viable.
 2. Returns the sum of the matrices.
 3. Returns the differen of the matrices.
 4. Returns the element-wise multiplication of the matrices.
 5. Returns the element-wise division of the matrices.

Use 5 sample matrices in which their shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [32]:
def mat_operations(mat1, mat2):
    mat1 = np.array(mat1)
    mat2 = np.array(mat2)
    print('Matrix 1:', mat1)
    print('Matrix 2:', mat2)
    if(mat1.shape != mat2.shape):
        print('The matrices are not equal and invalid size operation.')
        return
    print('Sum of the  matrices:')
    matsum = mat1 + mat2
    print(matsum)
    print('Difference of the  matrices:')
    matdiff = mat1 - mat2
    print(matdiff)
    print('Element-wise multiplication of the  matrices:')
    matmul = np.multiply(mat1, mat2)
    print(matmul)
    print('Element-wise division of the  matrices:')
    matdiv = np.divide(mat1, mat2)
    print(matdiv)

In [33]:
print('sample1:')
mat_operations([
    [1,2,3],
    [4,5,6],
    [7,8,9]],
    [[1,2,3],
    [4,5,6],
    [7,8,9]
])
print('sample 2:')
mat_operations([
    [9, 8, 7,6],
    [5,4,3,2],
    [1,9,8,7]],
    [[6,5,4,3],
    [2,1,1,2],
    [3,4,5,6]
])
print('sample 3:')
mat_operations([
    [1,2,3],
    [4,5,6],
    [7,8,9]],
    [[1,2,3],
    [4,5,6],
    [7,8,9]
])
print('sample 4:')
mat_operations([
    [1,2,3,4,5],
    [6,7,8,9,0],
    [1,2,3,4,5]],
    [[6,7,5,9,0],
    [1,2,3,4,5],
    [6,7,8,9,0]
])
print('sample 5:')
mat_operations([
    [0,1,2,3,4,5],
    [6,7,8,9,0,1],
    [2,3,4,5,6,7]],
    [[8,9,0,1,2,3],
    [4,5,7,8,9,0],
    [1,2,3,4,5,6]
])

sample1:
Matrix 1: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix 2: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of the  matrices:
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
Difference of the  matrices:
[[0 0 0]
 [0 0 0]
 [0 0 0]]
Element-wise multiplication of the  matrices:
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
Element-wise division of the  matrices:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
sample 2:
Matrix 1: [[9 8 7 6]
 [5 4 3 2]
 [1 9 8 7]]
Matrix 2: [[6 5 4 3]
 [2 1 1 2]
 [3 4 5 6]]
Sum of the  matrices:
[[15 13 11  9]
 [ 7  5  4  4]
 [ 4 13 13 13]]
Difference of the  matrices:
[[ 3  3  3  3]
 [ 3  3  2  0]
 [-2  5  3  1]]
Element-wise multiplication of the  matrices:
[[54 40 28 18]
 [10  4  3  4]
 [ 3 36 40 42]]
Element-wise division of the  matrices:
[[1.5        1.6        1.75       2.        ]
 [2.5        4.         3.         1.        ]
 [0.33333333 2.25       1.6        1.16666667]]
sample 3:
Matrix 1: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix 2: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of the  matrices:
[[ 2  4  6]
 [ 8

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: RuntimeWarning: divide by zero encountered in true_divide
